name: fintelligence_env
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.11.8
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - appdirs==1.4.4
      - attrs==23.2.0
      - beautifulsoup4==4.12.3
      - cattrs==23.2.3
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - frozendict==2.4.0
      - html5lib==1.1
      - idna==3.6
      - lxml==5.1.0
      - multitasking==0.0.11
      - numpy==1.26.4
      - pandas==2.2.1
      - peewee==3.17.1
      - platformdirs==4.2.0
      - pyrate-limiter==2.10.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - requests==2.31.0
      - requests-cache
      - requests-ratelimiter==0.6.0
      - six==1.16.0
      - soupsieve==2.5
      - tzdata==2024.1
      - url-normalize==1.4.3
      - urllib3==2.2.1
      - webencodings==0.5.1
      - yfinance==0.2.37
